### ISSUE TITLE
Telegram BOT interaction

### ISSUE THREAD

**Issue by mattia-baroni** [R3D4NG3L/PersonalExpenseReport#1]
Hi, after following the whole procedure if I try to write to the bot it doesn't give me any response (not even the authorisation error). The logs are written correctly, I don't know why the bot doesn't work.

**Comment by R3D4NG3L** [comment]
Hi,
thank you for the notificaiton.

In tag 1.0.1 has been updated Readme with missing steps.
Has been added also locale functionality.

For diffs take a look to this link:
https://github.com/R3D4NG3L/PersonalExpenseReport/compare/1.0.0...1.0.1

**Comment by mattia-baroni** [comment]
Hi,
Thank you for information, but I've already used version 1.0.1 and it doesn't work.
The telegram BOT doesn't respond.

**Comment by R3D4NG3L** [comment]
Could you post please errors reported in AppScript console while execution ReadMe step 7 (Execute getMe and setWebhook functions)?

**Comment by mattia-baroni** [comment]
I've no errors..
<img width="1149" alt="Schermata 2022-03-01 alle 10 59 40" src="https://user-images.githubusercontent.com/74552047/156147852-4633ac4a-2b9d-467a-960d-00bad15259ab.png">
<img width="1095" alt="Schermata 2022-03-01 alle 10 58 26" src="https://user-images.githubusercontent.com/74552047/156147846-3c387c88-c56f-49c9-82b6-67e2df41100d.png">

**Comment by mattia-baroni** [comment]
I've no errors
<img width="1095" alt="Schermata 2022-03-01 alle 10 58 26" src="https://user-images.githubusercontent.com/74552047/156148543-72f76ab2-f5a0-40bd-b0e2-3499d0584be2.png">
<img width="1149" alt="Schermata 2022-03-01 alle 10 59 40" src="https://user-images.githubusercontent.com/74552047/156148564-84e23224-5373-4a90-a3a7-f16bdd24b463.png">

**Comment by R3D4NG3L** [comment]
Could you confirm that the Web App has been deployed with authorization access "Everyone"? (ReadMe Step 4. Deploy App Script as Web Application)
Could you confirm that after having updatest the tokens the web app deployment has been updated? (ReadMe Step 6. Update App Script Deployment)

**Comment by mattia-baroni** [comment]
now is working, thank you!

**Comment by R3D4NG3L** [comment]
Thank you for the feedback.
May I ask you which was the action that lead to solve the problem? It could be useful for other users.

Thank you again!
